-- Koenigsegg CC850 Engage Shift System (ESS) + Drive-mode tuning
-- CSP car physics script — must live at <car>/data/script.lua
--
-- Requires:
--   * CSP 0.3.0-preview210 or newer (uses ac.overrideSpecificValue)
--   * car.ini -> [HEADER] VERSION=extended-2
--   * drivetrain.ini -> [GEARBOX] SUPPORTS_SHIFTER=1
--   * strongly recommended: [DOWNSHIFT_PROTECTION] ACTIVE=0 and
--     [DAMAGE] RPM_WINDOW_K=0 (AC's internal box is cosmetic here, but it
--     must never refuse a shift or take phantom damage)
--
-- Native-first design: AC's own gearbox IS the virtual 6-speed the player
-- sees. Paddle presses pass through to AC normally (native animation, UI,
-- sounds) and are only swallowed at the virtual limits (slot 6 up, R down).
-- The actual physics is mapped underneath by forcing the engaged gear every
-- frame, so slot N drives a different physical LST gear per profile:
--   NORMAL: LST 2, 4, 6, 7, 8, 9 + soft throttle + baseline dampers
--   TRACK:  LST 3, 4, 5, 6, 7, 8 + linear throttle + stiffer dampers
--   (EXTRA_A toggles profile)
-- AUTO (D): EXTRA_C toggle (or slot 7 with an H-pattern shifter). Paddles
-- are inert, the script shifts all nine physical gears by RPM, and no
-- cosmetic overrides are applied at all.

local H_PATTERN              = false  -- set true for an H-pattern shifter
local REVERSE_MAX_KMH        = 5      -- only shift into R below this speed
local MANUAL_SHIFT_TIME      = 0.04   -- LST engages near-instantly in manual
local PULSE_INTERVAL         = 0.15   -- s between resync pulses
local MAX_PULSES             = 8      -- hard cap per slot change; cannot loop
local CLUTCH_OPEN_THRESHOLD  = 0.3    -- carPh.clutch below this = drivetrain
                                      -- decoupled. AC's controller autoclutch
                                      -- and a real clutch pedal both write
                                      -- this field, so honoring it gives
                                      -- correct behavior in both cases.

local PROFILES = {
  NORMAL = {
    gears        = { 2, 4, 6, 7, 8, 9 },
    throttleExp  = 1.35,   -- > 1 softens initial pedal travel
    upshiftRpm   = 7400,
    downshiftRpm = 2400,
    shiftTime    = 0.10,
    cooldown     = 0.45,
    damping      = {       -- multipliers vs baseline from suspensions.ini
      reboundSlow = 1.00, reboundFast = 1.00,
      bumpSlow    = 1.00, bumpFast    = 1.00,
    },
  },
  TRACK = {
    gears        = { 3, 4, 5, 6, 7, 8 },
    throttleExp  = 1.00,   -- linear pedal in Track
    upshiftRpm   = 8200,
    downshiftRpm = 3200,
    shiftTime    = 0.04,
    cooldown     = 0.25,
    damping      = {
      reboundSlow = 1.20, reboundFast = 1.10,
      bumpSlow    = 1.15, bumpFast    = 1.05,
    },
  },
}

local carPh = ac.accessCarPhysics()

-- Physics-side internal gear, raw convention: 0=R, 1=N, 2=1st...
-- (don't use car.gear here: graphics-side values can lag or be overridden)
local hasCarPhGear = pcall(function() return carPh.gear end)

-- Read drivetrain numbers so the ini stays the single source of truth
local cfg = ac.INIConfig.carData(car.index, 'drivetrain.ini')
local finalRatio = cfg:get('GEARS', 'FINAL', 3.2)
local gearsCount = cfg:get('GEARS', 'COUNT', 9)
local ratios = {}
for i = 1, gearsCount do
  ratios[i] = cfg:get('GEARS', 'GEAR_%d' % i, 1)
end

-- Damper access only exists in CSP's autogenerated bindings; probe and
-- degrade gracefully (see 'ESS damper API' in the Lua Debug app)
local dampers = {}
local damperBase = {}
local function tryAccessDampers()
  local probes = { 'accessCarDamper', 'accessDamper', 'accessCarDampers' }
  for _, name in ipairs(probes) do
    if type(ac[name]) == 'function' then
      local ok, first = pcall(ac[name], 0)
      if ok and first ~= nil then
        for w = 0, 3 do
          local _, d = pcall(ac[name], w)
          if d == nil then return nil end
          dampers[w] = d
          damperBase[w] = {
            reboundSlow = d.reboundSlow, reboundFast = d.reboundFast,
            bumpSlow    = d.bumpSlow,    bumpFast    = d.bumpFast,
          }
        end
        return name
      end
    end
  end
  return nil
end
local damperApi = tryAccessDampers()

local hasOverride = ac.CarPhysicsValueID ~= nil and ac.overrideSpecificValue ~= nil
  and ac.setGearsFinalRatio ~= nil

-- Clutch-coupling overrides (same ones CSP's automatic-transmission module
-- uses to hard-lock the drivetrain when cruising — without them the
-- override-driven drivetrain never fully locks and slips a few percent,
-- felt most in high gears)
local idClutchOverride, idOpenThreshold
do
  local ok1, v1 = pcall(function() return ac.CarPhysicsValueID.DrivetrainClutchOverride end)
  local ok2, v2 = pcall(function() return ac.CarPhysicsValueID.DrivetrainOpenThreshold end)
  if ok1 and v1 ~= nil and ok2 and v2 ~= nil then
    idClutchOverride, idOpenThreshold = v1, v2
  end
end

local profile    = 'NORMAL'
local autoMode   = false
local slot       = 0      -- virtual manual slot: -1 R, 0 N, 1..6
local autoGear   = 1
local cooldown   = 0
local engaged    = 0      -- physical gear engaged by the override
local blendMult  = 1
local blendPos   = 1
local blendFrom  = 1
local blendTime  = MANUAL_SHIFT_TIME
local extraAPrev, extraCPrev = false, false
local prevUp, prevDown = false, false
local injectedUp, injectedDown = false, false
local pulseTimer = 0
local pulseCount = 0
local slotPrev   = nil
local controlsWritable = nil
local lastProfile = nil
local warned = false

local function message(title, desc)
  if ac.setSystemMessage ~= nil then ac.setSystemMessage(title, desc) end
end

local function applyDamperProfile(p)
  if damperApi == nil then return end
  local m = p.damping
  for w = 0, 3 do
    local d, base = dampers[w], damperBase[w]
    d.reboundSlow = base.reboundSlow * m.reboundSlow
    d.reboundFast = base.reboundFast * m.reboundFast
    d.bumpSlow    = base.bumpSlow    * m.bumpSlow
    d.bumpFast    = base.bumpFast    * m.bumpFast
  end
end

local function enterAuto()
  autoMode = true
  autoGear = math.clamp(engaged, 1, gearsCount)
  cooldown = PROFILES[profile].cooldown
  message('ESS', 'AUTO (D) engaged')
end

local function exitAuto()
  autoMode = false
  if engaged <= 0 then
    slot = engaged
  else
    slot = 1
    for i = 1, 6 do
      if PROFILES[profile].gears[i] <= engaged then slot = i end
    end
  end
  message('ESS', profile .. ' profile engaged')
end

function script.reset()
  profile, autoMode, slot, autoGear = 'NORMAL', false, 0, 1
  cooldown, engaged, blendMult, blendPos = 0, 0, 1, 1
  pulseCount, slotPrev = 0, nil
  applyDamperProfile(PROFILES.NORMAL)
end

function script.update(dt)
  if not hasOverride then
    if not warned then
      warned = true
      message('ESS', 'CSP 0.3.0-preview210+ required for this car')
    end
    ac.debug('ESS error', 'ac.overrideSpecificValue unavailable, update CSP')
    return
  end

  local p = PROFILES[profile]
  cooldown = math.max(0, cooldown - dt)
  pulseTimer = math.max(0, pulseTimer - dt)

  -- ====================================================================
  -- 1. INPUTS
  -- ====================================================================
  local upEdge = carPh.gearUp and not prevUp
  local downEdge = carPh.gearDown and not prevDown
  prevUp, prevDown = carPh.gearUp, carPh.gearDown

  -- Don't mistake our own resync pulses for player input
  if injectedUp then upEdge, injectedUp = false, false end
  if injectedDown then downEdge, injectedDown = false, false end

  if controlsWritable == nil then
    controlsWritable = pcall(function() carPh.gearUp = carPh.gearUp end)
  end

  -- EXTRA_A: toggle manual profile
  if car.extraA ~= extraAPrev then
    extraAPrev = car.extraA
    if car.extraA then
      if autoMode then
        message('ESS', 'Leave D to change profiles')
      else
        profile = (profile == 'NORMAL') and 'TRACK' or 'NORMAL'
        message('ESS', profile .. ' profile engaged')
      end
    end
  end

  -- EXTRA_C: toggle AUTO (D)
  if car.extraC ~= extraCPrev then
    extraCPrev = car.extraC
    if car.extraC then
      if autoMode then exitAuto() else enterAuto() end
    end
  end

  -- ====================================================================
  -- 2. VIRTUAL SLOT + SELECTIVE PADDLE PASS-THROUGH
  -- ====================================================================
  -- In manual, legal presses go through untouched so AC's own gearbox
  -- shifts with them — that's what keeps animation/UI/sounds native.
  -- Only presses beyond the virtual limits (and everything in AUTO) get
  -- swallowed.
  if H_PATTERN then
    local raw = carPh.requestedGearIndex
    if raw == 8 then
      if not autoMode then enterAuto() end
    elseif raw >= 0 and raw <= 7 then
      if autoMode then exitAuto() end
      slot = raw - 1
    end
  elseif autoMode then
    if controlsWritable then
      carPh.gearUp, carPh.gearDown = false, false
    end
  else
    local downFloor = (car.speedKmh < REVERSE_MAX_KMH) and -1 or 0
    if upEdge then
      if slot < 6 then
        slot = slot + 1
        pulseTimer = PULSE_INTERVAL  -- give AC time to process this press
      elseif controlsWritable then
        carPh.gearUp = false         -- virtual box tops out at 6
      end
    end
    if downEdge then
      if slot > downFloor then
        slot = slot - 1
        pulseTimer = PULSE_INTERVAL
      elseif controlsWritable then
        carPh.gearDown = false
      end
    end
  end

  -- ====================================================================
  -- 3. PROFILE-WIDE SETTINGS ON CHANGE
  -- ====================================================================
  if profile ~= lastProfile then
    lastProfile = profile
    applyDamperProfile(p)
  end

  -- ====================================================================
  -- 4. THROTTLE RESPONSE CURVE
  -- ====================================================================
  -- Skip while clutch is open: AC drives the throttle during autoblip
  -- on downshifts, and we don't want to exp-curve its blip down.
  if p.throttleExp ~= 1.0 and engaged > 0 and carPh.gas > 0
      and carPh.clutch >= CLUTCH_OPEN_THRESHOLD then
    carPh.gas = math.pow(carPh.gas, p.throttleExp)
  end

  -- ====================================================================
  -- 5. AUTO (D) SHIFT LOGIC
  -- ====================================================================
  if autoMode and cooldown == 0 then
    if carPh.rpm > p.upshiftRpm and autoGear < gearsCount then
      autoGear, cooldown = autoGear + 1, p.cooldown
    elseif carPh.rpm < p.downshiftRpm and autoGear > 1 then
      autoGear, cooldown = autoGear - 1, p.cooldown
    end
  end

  -- ====================================================================
  -- 6. ENGAGE THE TARGET GEAR (the actual physics)
  -- ====================================================================
  local target
  if autoMode then
    target = autoGear
  elseif slot <= 0 then
    target = slot
  else
    target = p.gears[slot]
  end

  if target ~= engaged then
    if engaged > 0 and target > 0 then
      blendFrom = ratios[engaged]
      blendPos = 0
      blendTime = autoMode and p.shiftTime or MANUAL_SHIFT_TIME
    else
      blendPos = 1
    end
    engaged = target
  end

  if blendPos < 1 and engaged > 0 then
    blendPos = math.min(1, blendPos + dt / blendTime)
    local ideal = math.lerp(blendFrom, ratios[engaged], blendPos)
    blendMult = ideal / ratios[engaged]
  else
    blendMult = 1
  end

  -- Clutch handling. Preferred path: drive the drivetrain clutch coupling
  -- directly from carPh.clutch (controller autoclutch and a real pedal both
  -- write that field) and hard-lock it whenever the clutch is fully home —
  -- this is what stops the constant few-percent slip in high gears.
  -- Fallback path (older CSP): drop the override to raw neutral while the
  -- clutch is open so the dip at least decouples the drivetrain.
  local clutch = math.saturate(carPh.clutch)
  local rawGear = engaged + 1
  if idClutchOverride ~= nil then
    local locked = clutch > 0.99
    ac.overrideSpecificValue(idClutchOverride, clutch)
    ac.overrideSpecificValue(idOpenThreshold, locked and 0.05 or 0)
  elseif not autoMode and clutch < CLUTCH_OPEN_THRESHOLD then
    rawGear = 1            -- raw neutral
  end
  ac.overrideSpecificValue(ac.CarPhysicsValueID.DrivetrainEngagedGear, rawGear)
  ac.setGearsFinalRatio(finalRatio * blendMult)

  -- ====================================================================
  -- 7. RESYNC WALKER (manual only)
  -- ====================================================================
  -- Normally AC's box tracks the slot by itself since legal presses pass
  -- through. Drift only appears after leaving D or if AC refused a shift;
  -- walk it back with strictly capped pulses. No display overrides, ever.
  local internal = hasCarPhGear and carPh.gear or nil
  if internal ~= nil and not H_PATTERN and not autoMode and controlsWritable then
    if slot ~= slotPrev then
      slotPrev = slot
      pulseCount = 0
    end
    local wantRaw = slot + 1  -- raw convention: 0=R, 1=N, 2=1st
    if internal ~= wantRaw and pulseTimer == 0 and pulseCount < MAX_PULSES then
      if internal < wantRaw then
        carPh.gearUp, injectedUp = true, true
      else
        carPh.gearDown, injectedDown = true, true
      end
      pulseCount = pulseCount + 1
      pulseTimer = PULSE_INTERVAL
    end
  end

  -- ====================================================================
  -- 8. DEBUG
  -- ====================================================================
  ac.debug('ESS mode', autoMode and 'AUTO (D)' or ('MANUAL ' .. profile))
  ac.debug('ESS virtual slot', slot)
  ac.debug('ESS engaged physical gear', engaged)
  ac.debug('ESS internal raw gear (carPh)', internal or 'n/a')
  ac.debug('ESS damper API', damperApi or 'NOT AVAILABLE')
  ac.debug('ESS controls writable', controlsWritable)
  ac.debug('ESS rpm', carPh.rpm)
  ac.debug('ESS clutch (1=engaged 0=open)', carPh.clutch)
  ac.debug('ESS clutch lock path', idClutchOverride ~= nil and 'direct override' or 'neutral fallback')
end
