-- Koenigsegg CC850 Engage Shift System (ESS) + Drive-mode tuning
-- CSP car physics script — must live at <car>/data/script.lua
--
-- Requires:
--   * CSP 0.3.0-preview210 or newer (uses ac.overrideSpecificValue)
--   * car.ini -> [HEADER] VERSION=extended-2
--   * drivetrain.ini -> [GEARBOX] SUPPORTS_SHIFTER=1
--
-- The script runs a virtual 6-speed gearbox on top of the physical 9-speed
-- LST by forcing the engaged gear directly every physics frame (same
-- technique as CSP's shared automatic-transmission module), so it works
-- identically with paddles, keyboard or an H-pattern shifter.
--
-- Each profile bundles gear mapping + throttle response + shift behavior
-- + (best-effort) damper stiffness:
--   NORMAL: slots 1-6 -> LST 2, 4, 6, 7, 8, 9, softer throttle, baseline dampers
--   TRACK:  slots 1-6 -> LST 3, 4, 5, 6, 7, 8, linear throttle, stiffer dampers
-- Toggle with EXTRA_A. EXTRA_C engages AUTO (D); with an H-pattern shifter the
-- top gate (7) does the same. D shifts through all nine LST gears by RPM.
--
-- Controller type is auto-detected each frame — no flag to set. An H-pattern
-- shifter moves requestedGearIndex directly; paddles/sequential use gearUp/Down
-- edges (which we swallow), so the two never get confused.

local REVERSE_MAX_KMH   = 5      -- only shift into R below this speed
local MANUAL_SHIFT_TIME = 0.04   -- LST engages near-instantly in manual
local SHOW_VIRTUAL_GEAR = true   -- dash shows slot number, not physical gear
local CLUTCH_HARD_LOCK  = true   -- forcing the engaged gear leaves the clutch
                                 -- coupling a few % open (worst in tall gears);
                                 -- this hard-locks it while driving. Set false
                                 -- for plain V4 behavior (slip returns).
local CLUTCH_HOME       = 0.98   -- clutch at/above this counts as fully home

local PROFILES = {
  NORMAL = {
    gears        = { 2, 4, 6, 7, 8, 9 },
    throttleExp  = 1.35,   -- > 1 softens initial pedal travel
    upshiftRpm   = 7400,
    downshiftRpm = 2400,
    shiftTime    = 0.10,
    cooldown     = 0.45,
    damping      = {       -- multipliers vs baseline from suspensions.ini
      reboundSlow = 1.00, reboundFast = 1.00,
      bumpSlow    = 1.00, bumpFast    = 1.00,
    },
  },
  TRACK = {
    gears        = { 3, 4, 5, 6, 7, 8 },
    throttleExp  = 1.00,   -- linear pedal in Track
    upshiftRpm   = 8200,
    downshiftRpm = 3200,
    shiftTime    = 0.04,
    cooldown     = 0.25,
    damping      = {
      reboundSlow = 1.20, reboundFast = 1.10,
      bumpSlow    = 1.15, bumpFast    = 1.05,
    },
  },
}

local carPh = ac.accessCarPhysics()

-- carPh.gear is the raw gear AC has actually engaged (0=R, 1=N, 2=1st). It isn't
-- exposed on every build, so probe once. The H-pattern ratio correction uses it.
local hasCarPhGear = pcall(function() return carPh.gear end)

-- Read drivetrain numbers so the ini stays the single source of truth
local cfg = ac.INIConfig.carData(car.index, 'drivetrain.ini')
local finalRatio = cfg:get('GEARS', 'FINAL', 3.2)
local gearsCount = cfg:get('GEARS', 'COUNT', 9)
local ratios = {}
for i = 1, gearsCount do
  ratios[i] = cfg:get('GEARS', 'GEAR_%d' % i, 1)
end

-- Try to grab damper handles (accessor name only appears in CSP's
-- autogenerated bindings — probe several plausible names so we degrade
-- gracefully on builds that don't expose it).
local dampers = {}
local damperBase = {}  -- baseline values so multipliers compose cleanly
local function tryAccessDampers()
  local probes = { 'accessCarDamper', 'accessDamper', 'accessCarDampers' }
  for _, name in ipairs(probes) do
    if type(ac[name]) == 'function' then
      local ok, first = pcall(ac[name], 0)
      if ok and first ~= nil then
        for w = 0, 3 do
          local _, d = pcall(ac[name], w)
          if d == nil then return nil end
          dampers[w] = d
          damperBase[w] = {
            reboundSlow = d.reboundSlow, reboundFast = d.reboundFast,
            bumpSlow    = d.bumpSlow,    bumpFast    = d.bumpFast,
          }
        end
        return name
      end
    end
  end
  return nil
end
local damperApi = tryAccessDampers()

local hasOverride = ac.CarPhysicsValueID ~= nil and ac.overrideSpecificValue ~= nil
  and ac.setGearsFinalRatio ~= nil

-- Clutch-coupling override IDs. The DrivetrainEngagedGear override alone never
-- fully locks the drivetrain clutch — it slips a few percent, felt most in tall
-- gears. These are the same values CSP's automatic-transmission module uses to
-- force a full lock. Probe gracefully: they aren't exposed on every build, and
-- without them we fall back to plain (slipping) behavior.
local idClutchOverride, idOpenThreshold
do
  local ok1, v1 = pcall(function() return ac.CarPhysicsValueID.DrivetrainClutchOverride end)
  local ok2, v2 = pcall(function() return ac.CarPhysicsValueID.DrivetrainOpenThreshold end)
  if ok1 and v1 ~= nil and ok2 and v2 ~= nil then
    idClutchOverride, idOpenThreshold = v1, v2
  end
end

local profile    = 'NORMAL'
local autoMode   = false
local slot       = 0      -- virtual manual slot: -1 R, 0 N, 1..6
local autoGear   = 1
local cooldown   = 0
local engaged    = 0
local blendMult  = 1
local blendPos   = 1
local blendFrom  = 1
local blendTime  = MANUAL_SHIFT_TIME
local extraAPrev, extraCPrev = false, false
local prevUp, prevDown = false, false
local controlsWritable = nil
local requestedWritable = nil
local lastRaw    = nil     -- previous requestedGearIndex, to spot H-shifter moves
local lastInput  = 'none'  -- 'H-pattern' or 'sequential', auto-detected
local lastProfile = nil
local warned = false

local function message(title, desc)
  if ac.setSystemMessage ~= nil then ac.setSystemMessage(title, desc) end
end

local function applyDamperProfile(p)
  if damperApi == nil then return end
  local m = p.damping
  for w = 0, 3 do
    local d, base = dampers[w], damperBase[w]
    d.reboundSlow = base.reboundSlow * m.reboundSlow
    d.reboundFast = base.reboundFast * m.reboundFast
    d.bumpSlow    = base.bumpSlow    * m.bumpSlow
    d.bumpFast    = base.bumpFast    * m.bumpFast
  end
end

local function enterAuto()
  autoMode = true
  autoGear = math.clamp(car.gear, 1, gearsCount)
  cooldown = PROFILES[profile].cooldown
  message('ESS', 'AUTO (D) engaged')
end

local function exitAuto()
  autoMode = false
  if engaged <= 0 then
    slot = engaged
  else
    slot = 1
    for i = 1, 6 do
      if PROFILES[profile].gears[i] <= engaged then slot = i end
    end
  end
  message('ESS', profile .. ' profile engaged')
end

function script.reset()
  profile, autoMode, slot, autoGear = 'NORMAL', false, 0, 1
  cooldown, engaged, blendMult, blendPos = 0, 0, 1, 1
  applyDamperProfile(PROFILES.NORMAL)
end

function script.update(dt)
  if not hasOverride then
    if not warned then
      warned = true
      message('ESS', 'CSP 0.3.0-preview210+ required for this car')
    end
    ac.debug('ESS error', 'ac.overrideSpecificValue unavailable, update CSP')
    return
  end

  local p = PROFILES[profile]
  cooldown = math.max(0, cooldown - dt)

  -- ====================================================================
  -- 1. INPUTS
  -- ====================================================================
  local upEdge = carPh.gearUp and not prevUp
  local downEdge = carPh.gearDown and not prevDown
  prevUp, prevDown = carPh.gearUp, carPh.gearDown

  if controlsWritable == nil then
    controlsWritable = pcall(function() carPh.gearUp = carPh.gearUp end)
  end
  if requestedWritable == nil then
    requestedWritable = pcall(function() carPh.requestedGearIndex = carPh.requestedGearIndex end)
  end
  if controlsWritable then
    carPh.gearUp, carPh.gearDown = false, false
  end

  -- EXTRA_A: toggle manual profile
  if car.extraA ~= extraAPrev then
    extraAPrev = car.extraA
    if car.extraA then
      if autoMode then
        message('ESS', 'Leave D to change profiles')
      else
        profile = (profile == 'NORMAL') and 'TRACK' or 'NORMAL'
        message('ESS', profile .. ' profile engaged')
      end
    end
  end

  -- EXTRA_C: toggle AUTO (D)
  if car.extraC ~= extraCPrev then
    extraCPrev = car.extraC
    if car.extraC then
      if autoMode then exitAuto() else enterAuto() end
    end
  end

  -- INPUT (auto-detected, no flag to set):
  -- * H-pattern shifter — writes the selected gate straight into
  --   requestedGearIndex, so any change there is a direct gate selection. With
  --   paddles we swallow gearUp/gearDown above, AC's box stays parked and this
  --   value never moves on its own, so the block is inert for paddle users.
  -- * Paddles / sequential — walk the slot by gearUp/gearDown edges.
  local raw = carPh.requestedGearIndex
  if lastRaw ~= nil and raw ~= lastRaw then
    lastInput = 'H-pattern'
    if raw == 8 then
      if not autoMode then enterAuto() end          -- top gate engages AUTO (D)
    elseif raw >= 0 and raw <= 7 then
      if autoMode then exitAuto() end
      slot = raw - 1                                 -- raw 1=N->0, 2..7->gates 1..6
    end
  end
  lastRaw = raw

  if not autoMode then
    if upEdge or downEdge then lastInput = 'sequential' end
    if upEdge then slot = math.min(slot + 1, 6) end
    if downEdge then
      local floor = (car.speedKmh < REVERSE_MAX_KMH) and -1 or 0
      slot = math.max(slot - 1, floor)
    end
  end

  -- ====================================================================
  -- 2. APPLY PROFILE-WIDE SETTINGS WHEN IT CHANGES
  -- ====================================================================
  if profile ~= lastProfile then
    lastProfile = profile
    applyDamperProfile(p)
  end

  -- ====================================================================
  -- 3. THROTTLE RESPONSE CURVE
  -- ====================================================================
  -- Reshape the gas pedal: y = x^throttleExp. Normal gets a softer curve,
  -- Track passes through linearly. Skip in R/N so creep behavior is intact.
  if p.throttleExp ~= 1.0 and engaged > 0 and carPh.gas > 0 then
    carPh.gas = math.pow(carPh.gas, p.throttleExp)
  end

  -- ====================================================================
  -- 4. AUTO (D) SHIFT LOGIC
  -- ====================================================================
  if autoMode and cooldown == 0 then
    if carPh.rpm > p.upshiftRpm and autoGear < gearsCount then
      autoGear, cooldown = autoGear + 1, p.cooldown
    elseif carPh.rpm < p.downshiftRpm and autoGear > 1 then
      autoGear, cooldown = autoGear - 1, p.cooldown
    end
  end

  -- ====================================================================
  -- 5. ENGAGE THE TARGET GEAR
  -- ====================================================================
  local target
  if autoMode then
    target = autoGear
  elseif slot <= 0 then
    target = slot
  else
    target = p.gears[slot]
  end

  if target ~= engaged then
    if engaged > 0 and target > 0 then
      blendFrom = ratios[engaged]
      blendPos = 0
      blendTime = autoMode and p.shiftTime or MANUAL_SHIFT_TIME
    else
      blendPos = 1
    end
    engaged = target
  end

  if blendPos < 1 and engaged > 0 then
    blendPos = math.min(1, blendPos + dt / blendTime)
    local ideal = math.lerp(blendFrom, ratios[engaged], blendPos)
    blendMult = ideal / ratios[engaged]
  else
    blendMult = 1
  end

  ac.overrideSpecificValue(ac.CarPhysicsValueID.DrivetrainEngagedGear, engaged + 1)
  ac.setGearsFinalRatio(finalRatio * blendMult)

  -- H-pattern: drive AC's own gearbox to the MAPPED gear (not the raw gate), so
  -- the real ratio is the mapped gear's. AC's box gear is what sets the ratio —
  -- when the box sits in a gear the override alone doesn't change it — so e.g.
  -- gate 1 in TRACK must put AC's box in 3rd (engaged), giving 3rd's ratio.
  -- We don't touch lastRaw: AC re-samples the physical gate into
  -- requestedGearIndex before the next frame's read (section 1), so writing the
  -- mapped gear here doesn't disturb gate reading (the dog-leg remap pattern).
  -- AUTO and sequential are left untouched.
  if lastInput == 'H-pattern' and not autoMode and requestedWritable then
    carPh.requestedGearIndex = engaged + 1   -- raw: 0=R, 1=N, 2=1st, ...
  end

  -- ====================================================================
  -- 5b. CLUTCH HARD-LOCK (kills the override-driven drivetrain slip)
  -- ====================================================================
  -- Only lock when actually in a forward gear with the clutch fully home. In
  -- N/R, or while the player is genuinely declutching (launch / stop), we track
  -- the real clutch instead so creep, clutch starts and stalling stay intact.
  local clutch = math.saturate(carPh.clutch)
  local lockState = 'off'
  if CLUTCH_HARD_LOCK and idClutchOverride ~= nil then
    if engaged > 0 and clutch >= CLUTCH_HOME then
      ac.overrideSpecificValue(idClutchOverride, 1.0)   -- couple fully
      ac.overrideSpecificValue(idOpenThreshold, 0.05)   -- only open below 0.05
      lockState = 'LOCKED'
    else
      ac.overrideSpecificValue(idClutchOverride, clutch)
      ac.overrideSpecificValue(idOpenThreshold, 0)
      lockState = 'tracking (N/R or declutch)'
    end
  elseif CLUTCH_HARD_LOCK then
    lockState = 'ID NOT FOUND'
  end

  -- ====================================================================
  -- 6. DISPLAY + DEBUG
  -- ====================================================================
  if SHOW_VIRTUAL_GEAR then
    ac.overrideCarState('gear', autoMode and autoGear or slot)
  end

  ac.debug('ESS mode', autoMode and 'AUTO (D)' or ('MANUAL ' .. profile))
  ac.debug('ESS DIAG', string.format(
    'input=%s  requested=%s  slot=%s  engaged=%s  AC_gear=%s',
    lastInput, tostring(carPh.requestedGearIndex), tostring(slot),
    tostring(engaged), tostring(hasCarPhGear and carPh.gear or 'n/a')))
  ac.debug('ESS detected input', lastInput)
  ac.debug('ESS virtual slot', slot)
  ac.debug('ESS engaged physical gear', engaged)
  ac.debug('ESS requestedGearIndex (raw)', carPh.requestedGearIndex)
  ac.debug('ESS AC engaged gear (raw)', hasCarPhGear and carPh.gear or 'n/a')
  ac.debug('ESS damper API', damperApi or 'NOT AVAILABLE')
  ac.debug('ESS controls writable', controlsWritable)
  ac.debug('ESS rpm', carPh.rpm)
  ac.debug('ESS clutch (1=home 0=open)', carPh.clutch)
  ac.debug('ESS drivetrain lock', lockState)
end
